name: Package and create artifact
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  alpha:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Package
        uses: BigWigsMods/packager@v2
        with:
          args: -z

      - name: Get short commit sha
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExtraQuestButton-${{ steps.sha.outputs.sha_short }}
          path: .release/
